name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  terraform-ci:
    name: Terraform CI Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Linting - Format Check
        run: terraform fmt -check

      - name: Linting - TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint .

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Security - tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Cost Estimation - Infracost Breakdown
        uses: infracost/actions@v2
        with:
          path: .
          format: json
          save-to: infracost-breakdown.json

      - name: Upload Infracost Report
        uses: actions/upload-artifact@v3
        with:
          name: infracost-report
          path: infracost-breakdown.json

      - name: Drift Detection - Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Upload Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: tfplan.binary

  terraform-cd:
    name: Terraform CD Pipeline
    needs: terraform-ci
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Download Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: .

      - name: Terraform Init
        run: terraform init

#      - name: Terraform Apply in Controlled Env
#        run: terraform apply -auto-approve tfplan.binary

      - name: Post-Deployment Verification - Smoke Test
        run: |
          echo "Testing provisioned load balancer endpoint"
          curl --fail --max-time 10 https://your-lb-endpoint.com || echo "Smoke test failed!"

      - name: Upload Terraform Logs and State
        run: |
          terraform show > terraform-output.log
        continue-on-error: true

      - name: Upload Terraform Output as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: terraform-outputs
          path: terraform-output.log
